# Generated by Django 5.1.1 on 2025-06-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_email_isverified_userdata_is_emailverified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='avatar_id',
            field=models.IntegerField(default=1),
        ),
    ]
