# Generated by Django 5.1.1 on 2025-06-23 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userdata_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
