# Generated by Django 5.1.1 on 2025-06-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_is_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_created',
            new_name='created_at',
        ),
    ]
