# Generated by Django 5.2.3 on 2025-06-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_is_created_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
