# Generated by Django 5.2.3 on 2025-06-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
