# Generated by Django 5.2.3 on 2025-06-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_post_likes'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS pg_trgm;"),
    ]
