# Generated by Django 5.2.3 on 2025-06-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20250627_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
